### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DenielWorld** [tedo0627/RedstoneCircuit#1]
Your plugin already seems awesome to me, and like something not many could do. I would like to request for you to add pistons to your plugin, which would make this plugin complete! Thank you.
[ENHANCEMENT]

**Comment by tedo0627** [comment]
I used google translate.
Thank you for request.
I tried to add a piston but I could not implementation the head part of the piston.
Somehow the head of the piston becomes transparent.
I would like to do my best if I have time and I can.

**Comment by DenielWorld** [comment]
Theres a plugin called Overvoltage, it has somewhat of the piston implemented, and you could use it as an example for making piston transparent. (It has base code, but not really fully implemented)

**Comment by tedo0627** [comment]
I found it but did not help.

**Comment by DenielWorld** [comment]
Could you add hoppers instead then?

**Comment by tedo0627** [comment]
ok

**Comment by DenielWorld** [comment]
Nice update! I see you made a progress on pistons, but they aren't fully implemented yet, right?

**Comment by DenielWorld** [comment]
New Bug Found: Lever doesnt work anymore in the new update

**Comment by tedo0627** [comment]
I work levar, but do I get an error?

**Comment by DenielWorld** [comment]
Its somewhat of an error in the log, but it doesn't direct you to any specific bug. Lever doesnt work, and doesn't change on/off

**Comment by DenielWorld** [comment]
You updated a lot of files last time, I can guess that you changed something in lever code that broke it, but it seems to look same as the last code from lever to me.

**Comment by DenielWorld** [comment]
Wait no, sorry the console error was related to something else. Lever doesn't have an error, but doesn't work

**Comment by tedo0627** [comment]
Please re-download this plugin from [Download ZIP].Please let me know if levar doesn't work.

**Comment by DenielWorld** [comment]
Ok

**Comment by DenielWorld** [comment]
Yes, it still does not work.

**Comment by tedo0627** [comment]
Please use /pl to check the plugin is included.

**Comment by DenielWorld** [comment]
It is, since all other redstone stuff works

**Comment by tedo0627** [comment]
Can you send me a screenshot or a video that lever doesn't work.

**Comment by DenielWorld** [comment]
Do you want to get on my server and see for yourself?

**Comment by tedo0627** [comment]
Yes, I want to see for myself.

**Comment by DenielWorld** [comment]
104.154.102.205 - ip
Port - 19125
Please join now

**Comment by DenielWorld** [comment]
I don't have much time, so it would be best if you got on right now :)

**Comment by tedo0627** [comment]
I was late to notice

**Comment by tedo0627** [comment]
Currently I am in your server.

**Comment by tedo0627** [comment]
(It resolved in the server.
