### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by JoshuaPHYT** [tedo0627/RedstoneCircuit#100]
Can you make redstone not to eat cpu too much. Only Ram or something

**Comment by tedo0627** [comment]
I have tried to figure out how to do that, but haven't come up with anything.

**Comment by JoshuaPHYT** [comment]
I have a question. Is this redstone plugin is gonna be lag if Many Players use this?

**Comment by tedo0627** [comment]
Lag does not increase with the number of players, but with the number and size of circuits operating.
I think that the lag increases as the number of hoppers and other tiles increases, because even if they are not operating, they are still processed as chunks are loaded
