### ISSUE TITLE
Hopper Duplication Bug

### ISSUE THREAD

**Issue by xodamcm** [tedo0627/RedstoneCircuit#103]
Hi, i found duplication bug with hopper, the bug occure when player put 2 hopper and throw item into the two dropper at the middle, i send you a video to see it directly

https://youtu.be/Yx9atJ3MaYs

**Comment by tedo0627** [comment]
I have fixed it.
Thank you.

**Comment by xodamcm** [comment]
Thank you to ! So fast 👌
