### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by NdaruAjaa** [tedo0627/RedstoneCircuit#108]
PocketMine-MP version: 4.15.2 [Protocol 567]
Git commit: 308cdb68631f1e4190d3741231e1219e80080e90
PHP version: 8.0.27
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: RedstoneCircuit

Error: Cannot set a block in un-generated terrain
File: pmsrc/src/world/World
Line: 1765
Type: pocketmine\world\WorldException

**Comment by tedo0627** [comment]
Show us the stack trace.

**Comment by NdaruAjaa** [comment]
I don't know I am not playing on the server that is playing is my member

**Comment by tedo0627** [comment]
Please show me a message like #98 that appears on the console with the error message

**Comment by NdaruAjaa** [comment]
A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: RedstoneCircuit

Error: Cannot set a block in un-generated terrain
File: pmsrc/src/world/World
Line: 1765
Type: pocketmine\world\WorldException
Backtrace:
#0 pmsrc/src/world/World(1747): pocketmine\world\World->setBlockAt(int -5238, int 80, int 2383, object tedo0627\redstonecircuit\block\mechanism\BlockMoving#1029963, true)
#1 plugins/RedstoneCircuit.phar/src/tedo0627/redstonecircuit/block/mechanism/BlockPiston(161): pocketmine\world\World->setBlock(object pocketmine\world\Position#985475, object tedo0627\redstonecircuit\block\mechanism\BlockMoving#1029963)
#2 plugins/RedstoneCircuit.phar/src/tedo0627/redstonecircuit/block/mechanism/BlockPiston(107): tedo0627\redstonecircuit\block\mechanism\BlockPiston->push()
#3 pmsrc/src/world/World(945): tedo0627\redstonecircuit\block\mechanism\BlockPiston->onScheduledUpdate()
#4 pmsrc/src/world/World(902): pocketmine\world\World->actuallyDoTick(int 882846)
#5 pmsrc/src/world/WorldManager(350): pocketmine\world\World->doTick(int 882846)
#6 pmsrc/src/Server(1810): pocketmine\world\WorldManager->tick(int 882846)
#7 pmsrc/src/Server(1692): pocketmine\Server->tick()
#8 pmsrc/src/Server(1053): pocketmine\Server->tickProcessor()
#9 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#10 pmsrc/src/PocketMine(362): pocketmine\server()
#11 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by tedo0627** [comment]
ok, I will check this issue when I have time

**Comment by NdaruAjaa** [comment]
Yaa

**Comment by tedo0627** [comment]
I could not reproduce the error, but I believe I could probably fix it.
Thank you.

**Comment by NdaruAjaa** [comment]
Hmm okay thanks
