### ISSUE TITLE
Piston ?

### ISSUE THREAD

**Issue by ghost** [tedo0627/RedstoneCircuit#12]
When will the pistons? and sticky pistons?

**Comment by DenielWorld** [comment]
The creator of the plugin will add them when she has the time, since those are very hard to implement. They are already somewhat being worked on.

**Comment by LeoBdt** [comment]
Ça veut rien dire ta question.... T'as de la change qu'ils t'ont compris

**Comment by LeoBdt** [comment]
Il/elle a ajouté les pistons. Tu peux fermer ton issue.
