### ISSUE TITLE
fireworks

### ISSUE THREAD

**Issue by CupidonSauce173** [tedo0627/RedstoneCircuit#14]
could you make it so the dispenser works with fireworks too ? Since its not implemented in pmmp
it would use a plugin like https://github.com/thebigsmileXD/fireworks/tree/master/
as a not necessary depency

**Comment by DenielWorld** [comment]
I believe it should already do that, since firework is a projectile and those are already inplemented.

**Comment by CupidonSauce173** [comment]
Oh, so this is an issue. Fireworks doesn't work with dispenser

**Comment by DenielWorld** [comment]
I might be able to add that myself, but there probably should be a config for it, since it will crash the server for those not using fireworks.

**Comment by CupidonSauce173** [comment]
Yes please, you would be my lover ;).

**Comment by dearminder** [comment]
how about adding a config to enable fireworks?

**Comment by LeoBdt** [comment]
Fireworks are implemented with teaspoon plugin

**Comment by tedo0627** [comment]
I implemented it.
