### ISSUE TITLE
Suggestion :)

### ISSUE THREAD

**Issue by LeoBdt** [tedo0627/RedstoneCircuit#18]
Hello, as we know pocketmine isn't optimised at all lol. Please can you add a limitation system. 

For example : 

Max_piston_per_world : 10
and it would cancel the 11th piston and say "you've reached the maximum number of piston (or something else like dropper) in the world" it'd avoid lags.

**Comment by LeoBdt** [comment]
And by the way, your plugin is very good, you're the first to made that ! Thanks !

**Comment by LeoBdt** [comment]
huh?

**Comment by tedo0627** [comment]
I implemented it.

**Comment by LeoBdt** [comment]
did you ? or are you going to ?

**Comment by tedo0627** [comment]
did.

**Comment by LeoBdt** [comment]
where's the update? Can't find it with me suggestions.

**Comment by tedo0627** [comment]
https://github.com/tedo0627/RedstoneCircuit_PMMP-Plugin/commit/dd8448fef007b9ef7ec25e4e0ea56e4ee749e7a8

**Comment by tedo0627** [comment]
I forgot update config.
https://github.com/tedo0627/RedstoneCircuit_PMMP-Plugin/commit/d60c931d259d60b89c27722dfd8a6548513e69ef

**Comment by LeoBdt** [comment]
Oof, u don't understand. That's a good add but that's not the topic of my issue. 

I want to set a limit PER WORLD for all Redstone stuff. For example, the maximum number  of dropper per world is 3. The maximum of repeater is 30....

It's to reduce lags. Do you understand ???

**Comment by LeoBdt** [comment]
oh and there's a duplication bug with piston. Just put item in chest and do a clock. 

Can you add an option to make piston off with chest/Hopper/trapped chest ....

**Comment by tedo0627** [comment]
I finally understood it. However, I thought it should not be implemented with this plugin.

I confirmed the bug. I will do my best to fix it as much as possible.

I will implements add option.

**Comment by LeoBdt** [comment]
Thanks

**Comment by tedo0627** [comment]
I added options.
