### ISSUE TITLE
Comparator loop 

### ISSUE THREAD

**Issue by UladzimirPetrachkiu** [tedo0627/RedstoneCircuit#2]
When I apply power to the comparator and close it myself to myself, as in the screenshot, the server freezes, and after a while it just reboots.
![image](https://user-images.githubusercontent.com/41127246/54635066-729cba80-4a94-11e9-8037-d9524cebd78f.png)

**Comment by tedo0627** [comment]
Thanks for the report.A little difficult but I will try to fix.

**Comment by tedo0627** [comment]
I fixed this bug.
