### ISSUE TITLE
Im making a modded survival and i needed this plugin but..

### ISSUE THREAD

**Issue by provsalt** [tedo0627/RedstoneCircuit#23]
I recently came accross this amazing pmmp plugin wonder how long it took
I am trying to ask for a more stable version so you can remove features that are more buggy and easily crash server
I think someone that could code redstone is going to change mcpe alot

**Comment by LeoBdt** [comment]
wtf you talkin about

**Comment by provsalt** [comment]
I mean by like less buggy version that doesn't crash when player makes asomething that breaks I can't be there 24/7 to on back the server

**Comment by LeoBdt** [comment]
just boot your server with ./start.sh -l

are you french?

**Comment by DenielWorld** [comment]
Why not define what exactly you find breaking the server so it can be fixed?

**Comment by LeoBdt** [comment]
exactly

**Comment by CupidonSauce173** [comment]
I think he just wants a config file where you can able / disable features like piston, droppers, etc.

**Comment by provsalt** [comment]
im using Pterodactyl panel so i can't use the terminal dude

**Comment by LeoBdt** [comment]
This plugin is good. If your server have poor performance we can't do anything.

**Comment by DenielWorld** [comment]
Pterodactyl panel is one of the easiest to use, and is what I use. I dont understand your problem. The panel lets you edit configuration files, so you can easily disable some features with the latest update of the plugin.

**Comment by LeoBdt** [comment]
i don't understand him too.

**Comment by provsalt** [comment]
oh now you can disable stuff alright i will put that updated version

**Comment by LeoBdt** [comment]
wtf please next time don't open a useless and inapprehensible issue....

**Comment by DenielWorld** [comment]
That's mean. Please next time speak for your own repositories xD

**Comment by LeoBdt** [comment]
yeah but i can't understand people that open issue without cheking plugin's updates xD

**Comment by DenielWorld** [comment]
We can't blame people who are new to this. Even tho they drive us crazy sometimes.

**Comment by LeoBdt** [comment]
true.
