### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by DenielWorld** [tedo0627/RedstoneCircuit#25]
1) Piston doesn't always push other piston, in some cases it doesn't. (Already extended piston cannot be pushed by a different piston)

2) Redstone may freeze if too many actions happen in a single area. (All actions happening will stay in activated form not depending on any power source)

3) Unconfirmed. Opening chest when its in movement of piston will cause an internal server error.

4) Piston doesn't always work. In some cases placing a piston and putting a lever on it and activating it, does not activate a piston.

**Comment by DenielWorld** [comment]
5. Daylight sensor does not function correctly.

**Comment by tedo0627** [comment]
1 In vanilla can't push the piston that is stretching.

2 It is the original specification. Running Redstone in php is wrong by itself.

Please explain concretely about 3, 4, 5.

**Comment by DenielWorld** [comment]
3) if a redstone clock is active on a piston, and the piston has a chest on it. If you open the chest while it works you will crash. Although this could possibly be caused by something else.

4) I placed a piston pretty high, put a lever on it and pressed. Piston did not activate. No block was in the way.

5) Daylight sensor doesn't change on day or night, but stays at its beginning state.

**Comment by DenielWorld** [comment]
6. Also I believe sticky piston doesnt work with pistons, doesnt pull them back. Not sure.

**Comment by DenielWorld** [comment]
7. Normal piston and slime block relation is not vanilla like. When a piston pushes slime block, and deactivates it is supossed to be pulled by slime block which it does not do.

**Comment by tedo0627** [comment]
I fixed bug 5.

**Comment by DenielWorld** [comment]
Thanks. Although bug 7 is a big one that breaks one of the vanilla redstone mechanics, would be good if you fixed it.

**Comment by DenielWorld** [comment]
8. Breaking blocks while they are moved by the piston (In a redstone cycle) results in drop of MovingBlock tile.

**Comment by DenielWorld** [comment]
9. IMPORTANT BUG> Moving a chest with a piston and quickly getting the item out of the chest before it moves back results in a dupe of the item.

**Comment by tedo0627** [comment]
I fixed bug 8.
About bug 7 it's a vanilla specification.

**Comment by DenielWorld** [comment]
Please fix 9, it also works with any block that has a chest like UI

**Comment by AlexPads** [comment]
Number 9 Works on SinglePlayer Aswell it is a Clent Side Rendering Game Communication error It has been Submitted to Mojang Many times and they are saying: "We are working on the bug" as usual.

**Comment by DenielWorld** [comment]
So is there no way to fix #9?

**Comment by DenielWorld** [comment]
9, not #9

**Comment by LeoBdt** [comment]
The way to fix it is to cancel chest moves if it pushs by a piston.

**Comment by DenielWorld** [comment]
Make it so if a person opens a chest then the chest cannot be moved by piston. That should fix 9 @tedo0627 , thanks

**Comment by DenielWorld** [comment]
Will this be updated for PMMP 4.0.0?

**Comment by Nat392** [comment]
Hello, I am the founder of a skyblock server and I have a bugg with your plugin. From time to time, in the players' cobblestone generator, the water and lava stops mixing. They are obliged to reverse the lava and the water so that it works again. And when I remove your plugin there is no longer the bugg.

**Comment by VoltageMC** [comment]
#9 is fixable as I fixed it myself :p
