### ISSUE TITLE
Many bugs.

### ISSUE THREAD

**Issue by LeoBdt** [tedo0627/RedstoneCircuit#29]
Hello.... Thanks for reading me.

1. Observer blocks doesn't working with growth (like pumpkin seeds...) 
2. This patern doesn't disable hoppers (go to https://drive.google.com/file/d/1ZvFvyv5oJVGxuqPdLl-pf-ap5xcC_KZP/view?usp=drivesdk )

**Comment by tedo0627** [comment]
I could not confirm bug 1.
About bug 2, I saw hopper is work like a picture. I think it may be in conflict with another plugin. Please unplug any plugins other than this one.

**Comment by LeoBdt** [comment]
I could confirm 1....

**Comment by DenielWorld** [comment]
Hoppers dont work if teaspoon is installed

**Comment by LeoBdt** [comment]
????
