### ISSUE TITLE
Duplication glitches

### ISSUE THREAD

**Issue by LeoBdt** [tedo0627/RedstoneCircuit#30]
hi, watch this please

https://youtu.be/A9h1CcwZHuo

**Comment by tedo0627** [comment]
I could not see the video

**Comment by LeoBdt** [comment]
It's with 2 piston and 1 chest...

**Comment by LeoBdt** [comment]
?

**Comment by tedo0627** [comment]
![image](https://user-images.githubusercontent.com/24734045/58376324-89372480-7fa3-11e9-8831-4addc057d772.png)
Click the URL and it will look like an image.
This means you can't play videos.

**Comment by RubyTemple** [comment]
yes this bug exist

**Comment by tedo0627** [comment]
Please tell me the details of the bug.

**Comment by PopGTN** [comment]
The player has to keep the chest movinf back and fourth while trying to grab the item they want to dupe before the chest moves
