### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by usser1976** [tedo0627/RedstoneCircuit#31]
Hi Tedo, sometimes we had a server crash.  Unfortunately we do not know why. 😕 This is the crash log:

PocketMine-MP Crash Dump Tue Apr 23 03:37:11 CEST 2019

Error: Call to a member function getBlockAt() on null
File: src/pocketmine/tile/Tile
Line: 258
Type: Error

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: RedstoneCircuit v2.0.0

Code:
[249] 	 */
[250] 	protected static function createAdditionalNBT(CompoundTag $nbt, Vector3 $pos, ?int $face = null, ?Item $item = null, ?Player $player = null) : void{
[251] 
[252] 	}
[253] 
[254] 	/**
[255] 	 * @return Block
[256] 	 */
[257] 	public function getBlock() : Block{
[258] 		return $this->level->getBlockAt($this->x, $this->y, $this->z);
[259] 	}
[260] 
[261] 	/**
[262] 	 * @return bool
[263] 	 */
[264] 	public function onUpdate() : bool{
[265] 		return false;
[266] 	}
[267] 
[268] 	final public function scheduleUpdate() : void{

Backtrace:
#0 plugins/RedstoneCircuit_dev-28.phar/src/redstone/blockEntities/BlockEntityChest(54): pocketmine\tile\Tile->getBlock()
#1 plugins/RedstoneCircuit_dev-28.phar/src/redstone/inventories/DoubleChestInventory(11): redstone\blockEntities\BlockEntityChest->onInventoryClose()
#2 src/pocketmine/inventory/BaseInventory(416): redstone\inventories\DoubleChestInventory->onClose(pocketmine\Player object)
#3 src/pocketmine/Player(3916): pocketmine\inventory\BaseInventory->close(pocketmine\Player object)
#4 src/pocketmine/Player(3932): pocketmine\Player->removeWindow(redstone\inventories\DoubleChestInventory object, boolean 1)
#5 src/pocketmine/Player(3518): pocketmine\Player->removeAllWindows(boolean 1)
#6 src/pocketmine/network/mcpe/RakLibInterface(177): pocketmine\Player->close(pocketmine\lang\TranslationContainer object, string Internal server error)
#7 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 82.82.104.96 42148, raklib\protocol\EncapsulatedPacket object, integer 0)
#8 src/pocketmine/network/mcpe/RakLibInterface(110): raklib\server\ServerHandler->handlePacket()
#9 src/pocketmine/network/mcpe/RakLibInterface(100): pocketmine\network\mcpe\RakLibInterface->process()
#10 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
#11 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
#12 src/pocketmine/Server(2338): pocketmine\snooze\SleeperHandler->sleepUntil(double 1555983431.8207)
#13 src/pocketmine/Server(2196): pocketmine\Server->tickProcessor()
#14 src/pocketmine/Server(1775): pocketmine\Server->start()
#15 src/pocketmine/PocketMine(258): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Server\Desktop\Sicherung neu\Pocketmine\, string C:\Users\Server\Desktop\Sicherung neu\Pocketmine\plugins\)
#16 (1): require(string phar://C:/Users/Server/Desktop/Sicherung neu/Pocketmine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.7.2 [Protocol 340]
Git commit: b4a8f8391b0fba26ed99bc5de0b3aaedcad4472f
uname -a: Windows NT SERVER-PC 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) AMD64
PHP Version: 7.2.13
Zend version: 3.2.0
OS : WINNT, win

If necessary, I can also send the output of the console

**Comment by DenielWorld** [comment]
Delete any private vaults plugin. I believe that could be one fix to the issue.

**Comment by usser1976** [comment]
We have a citybuild server with a lot of players, we can not delete many plugins and delete functions.  Then we can close 😔

**Comment by DenielWorld** [comment]
Its 1 plugin. Just have your players use ender chests instead.

**Comment by usser1976** [comment]
How does that work?  A player can only have one Ender chest 🤔 let's see what tedo says 😉

**Comment by tedo0627** [comment]
Maybe corrected. I could not reproduce this crash, so please let me know if the server crashes again.

**Comment by usser1976** [comment]
wow, really fast 😂 thanks 👍we will watch it.  I'll let you know when it happens again.  Good boy 🙂
