### ISSUE TITLE
Error on enabling RedstoneCircuit

### ISSUE THREAD

**Issue by RedCraftGH** [tedo0627/RedstoneCircuit#34]
Pocketmine version: 3.8.0

Error:
`Server thread/CRITICAL ErrorException: "file_get_contents(phar:///custom.phar/src/pocketmine/resources/vanilla/block_id_map.json): failed to open stream: phar error: "src/pocketmine/resources/vanilla/block_id_map.json" is not a file in phar "/custom.phar"" (EXCEPTION) in "plugins/RedstoneCircuit_dev-30.phar/src/redstone/utils/GlobalBlockPalette" at line 13
27.04 18:21:58 [Server] Server thread/DEBUG #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string file_get_contents(phar:///custom.phar/src/pocketmine/resources/vanilla/block_id_map.json): failed to open stream: phar error: "src/pocketmine/resources/vanilla/block_id_map.json" is not a file in phar "/custom.phar", string phar:///plugins/RedstoneCircuit_dev-30.phar/src/redstone/utils/GlobalBlockPalette.php, integer 13, array Array())
27.04 18:21:58 [Server] Server thread/DEBUG #1 plugins/RedstoneCircuit_dev-30.phar/src/redstone/utils/GlobalBlockPalette(13): file_get_contents(string phar:///custom.phar/src/pocketmine/resources/vanilla/block_id_map.json)
27.04 18:21:58 [Server] Server thread/DEBUG #2 plugins/RedstoneCircuit_dev-30.phar/src/redstone/Main(99): redstone\utils\GlobalBlockPalette->__construct()
27.04 18:21:58 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginBase(123): redstone\Main->onEnable()
27.04 18:21:58 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
27.04 18:21:58 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1993): pocketmine\plugin\PluginManager->enablePlugin(redstone\Main object)
27.04 18:21:58 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1979): pocketmine\Server->enablePlugin(redstone\Main object)
27.04 18:21:58 [Server] Server thread/DEBUG #7 plugins/DevTools.phar/src/DevTools/DevTools(73): pocketmine\Server->enablePlugins(integer 0)
27.04 18:21:58 [Server] Server thread/DEBUG #8 src/pocketmine/plugin/PluginBase(123): DevTools\DevTools->onEnable()
27.04 18:21:58 [Server] Server thread/DEBUG #9 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
27.04 18:21:58 [Server] Server thread/DEBUG #10 src/pocketmine/Server(1993): pocketmine\plugin\PluginManager->enablePlugin(DevTools\DevTools object)
27.04 18:21:58 [Server] Server thread/DEBUG #11 src/pocketmine/Server(1979): pocketmine\Server->enablePlugin(DevTools\DevTools object)
27.04 18:21:58 [Server] Server thread/DEBUG #12 src/pocketmine/Server(1712): pocketmine\Server->enablePlugins(integer 0)
27.04 18:21:58 [Server] Server thread/DEBUG #13 src/pocketmine/PocketMine(258): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
27.04 18:21:58 [Server] Server thread/DEBUG #14 (1): require(string phar:///custom.phar/src/pocketmine/PocketMine.php)`

**Comment by genboy** [comment]
@RedCraftGH Latest [dev update](https://poggit.pmmp.io/ci/tedo0627/RedstoneCircuit_PMMP-Plugin/RedstoneCircuit/dev:30) works fine with  PMMP version 3.8.1

**Comment by DenielWorld** [comment]
It was fixed in the latest commit

**Comment by Wertzui123** [comment]
Oh ok nice
