### ISSUE TITLE
Server Crash 😉

### ISSUE THREAD

**Issue by usser1976** [tedo0627/RedstoneCircuit#36]
We use the MyPlot plugin.  If on a plot are active redstone circuit and you have the plot cleart crashes the server.

PocketMine-MP Crash Dump Sun May 19 18:30:45 CEST 2019

Error: Call to undefined method pocketmine\block\Air::getInputFace()
File: plugins/RedstoneCircuit_dev-30.phar/src/redstone/blockEntities/BlockEntityRedstoneComparator
Line: 70
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: RedstoneCircuit v2.0.0

Code:

Backtrace:
#0 plugins/RedstoneCircuit_dev-30.phar/src/redstone/blockEntities/BlockEntityRedstoneComparator(43): redstone\blockEntities\BlockEntityRedstoneComparator->hasSideUtility()
#1 src/pocketmine/level/Level(863): redstone\blockEntities\BlockEntityRedstoneComparator->onUpdate()
#2 src/pocketmine/level/Level(794): pocketmine\level\Level->actuallyDoTick(integer 3237)
#3 src/pocketmine/Server(2435): pocketmine\level\Level->doTick(integer 3237)
#4 src/pocketmine/Server(2566): pocketmine\Server->checkTickUpdates(integer 3237, double 1558283445.9304)
#5 src/pocketmine/Server(2335): pocketmine\Server->tick()
#6 src/pocketmine/Server(2196): pocketmine\Server->tickProcessor()
#7 src/pocketmine/Server(1775): pocketmine\Server->start()
#8 src/pocketmine/PocketMine(258): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/, string /home/minecraft/plugins/)
#9 (1): require(string phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.8.1 [Protocol 354]
Git commit: 7521160f53b7568c5f74c93c566cf49d45219681
uname -a: Linux a72e61c0b99a 4.19.0-0.bpo.2-amd64 #1 SMP Debian 4.19.16-1~bpo9+1 (2019-02-07) x86_64
PHP Version: 7.2.16
Zend version: 3.2.0
OS : Linux, linux

**Comment by tedo0627** [comment]
If there is an error due to a conflict with another plugin, I am not sure if I will fix the bug.

**Comment by usser1976** [comment]
Okay, I can understand.  Too bad 🤔 If you delete active Comperator with world edit, that happens too.  Well the Comperatoren could be blocked 😉
