### ISSUE TITLE
Freeze redstone blocks

### ISSUE THREAD

**Issue by UladzimirPetrachkiu** [tedo0627/RedstoneCircuit#39]
When saving the world, for example, with the help of the command /save-all, the blocks of mechanisms stop responding to the signal (the pressure plates and buttons remain pressed). The mechanisms freeze immediately after saving, no server restart is required.
![image](https://user-images.githubusercontent.com/41127246/61123220-7b365800-a4ac-11e9-85b2-df77367a254d.png)
![image](https://user-images.githubusercontent.com/41127246/61123247-8b4e3780-a4ac-11e9-911e-abfcb42a5ba3.png)

**Comment by DenielWorld** [comment]
That is meant to happen unless you have disabled saving the states in config.

**Comment by aratorr** [comment]
So, when i disable saving the states in config, they continue to save

**Comment by UladzimirPetrachkiu** [comment]
Thanks, but it's a bug, right?

**Comment by tedo0627** [comment]
This bug cannot be fixed due to pmmp specifications.
