### ISSUE TITLE
Bugg

### ISSUE THREAD

**Issue by Nat392** [tedo0627/RedstoneCircuit#43]
Hello, I am the founder of a skyblock server and I have a bugg with your plugin. From time to time, in the players' cobblestone generator, the water and lava stops mixing. They are obliged to reverse the lava and the water so that it works again. And when I remove your plugin there is no longer the bugg.

**Comment by ElectroGamesDev** [comment]
SAmeee but Cobblestone Generators work.

**Comment by MistakingManx** [comment]
This in fact is a true issue, I had the same issue with my go on redstone and this plugin also caused it

**Comment by AGTHARN** [comment]
Please change,
**is-save-block-update: true** to **is-save-block-update: false** in config.yml that can be found in this plugin's data folder. This will fix the issue.

**Comment by Nat392** [comment]
Hello, I have another concern: after a restart, the players are forced to remove and put back their lava.

Do you have a fix?

**Comment by AGTHARN** [comment]
You mean after a restart, lava and water stops flowing?

**Comment by Nat392** [comment]
Yes
