### ISSUE TITLE
Repeaters Break every so often

### ISSUE THREAD

**Issue by ghost** [tedo0627/RedstoneCircuit#48]
Every so often a repeater freezes on or off, breaking the redstone contraption. Once you break and replace the repeater, the repeater cannot be activated.

**Comment by suerion** [comment]
here the same problem 


![problem redstone](https://user-images.githubusercontent.com/55131959/84169608-164aff80-aa79-11ea-83cb-6e39395dfdc6.PNG)
![problem redstone1](https://user-images.githubusercontent.com/55131959/84169611-177c2c80-aa79-11ea-879a-239fa561f590.PNG)

**Comment by suerion** [comment]
after destroying the clock, the repeater allways at on

if i replace it with an new repeater, it does not work

**Comment by ghost** [comment]
It is due to the event being called late within the plugin.
