### ISSUE TITLE
Pistons mit breakable!

### ISSUE THREAD

**Issue by MonoAdrian23** [tedo0627/RedstoneCircuit#50]
Pistons are not breakable, only with OP
RedstoneCircuit Latest
Pocketmine 3.12.2

**Comment by PopGTN** [comment]
Thats not the redstone plugin. I tested this on my server and it works in gms without op

**Comment by MonoAdrian23** [comment]
Xd, Only RedstoneCircuit implements Pistons.
This is a prob. Of RedstoneCircuit
