### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Wertzui123** [tedo0627/RedstoneCircuit#6]
1. You're plugin is awesome! Thanks!
2. Could you add:

-Pistons
-Minecarts
-Command Blocks
-Tripwire hooks
-Daylight sensors
-Redstone chests

And a bug. In the german version of the command block output windows the variables aren't replaced.

"%1$s*%2$d an %3$s gegeben"

**Comment by Wertzui123** [comment]
WHAT? Command Blocks work? Man! That's the best plugin I have ever seen!

**Comment by tedo0627** [comment]
I fixed command block output windows bug.
Pistons and Minecarts are difficult, but if I have time, I implement other than that.

**Comment by Wertzui123** [comment]
When pistons and minecarts will come I will be veryyy happy! That would change PmmP completly. And I have an Idea, how whould be 1. a permission for command blocks 2. deactivating command blocks in the config

**Comment by DenielWorld** [comment]
Its a plugin that implements vanilla redstone, so you need op to use command blocks. Aka permissions are not needed.

**Comment by Wertzui123** [comment]
Yes, that makes sens. But deactivating them would be linke in vanilla

**Comment by DenielWorld** [comment]
Explain deactivating part, I dont quiet get it

**Comment by Wertzui123** [comment]
I mean, there should be in the config

#Deactivating CommandBlocks
command-blocks-enabled= "true"

**Comment by Wertzui123** [comment]
And I have a new suggestion:

Hoppers should send a signal when there is an item in, like in vanilla!

**Comment by Wertzui123** [comment]
And a new suggestion:

If an item falls on a pressure plate, a redstone signal should be output.

**Comment by DenielWorld** [comment]
I think that already works

**Comment by Wertzui123** [comment]
It don't works for me

**Comment by Wertzui123** [comment]
So here again a full list of suggestions:

-Pistons
-Minecarts
-Tripwire hooks
-Daylight sensors
-Redstone chests
-Hoppers should send a signal when there is an item in, like in vanilla!
-If an item falls on a pressure plate, a redstone signal should be output
-Deactivating command blocks in the config

**Comment by tedo0627** [comment]
I Implemented except Pistons and Minecarts.

**Comment by Wertzui123** [comment]
Wow. Thank you very much!

**Comment by LeoBdt** [comment]
Tripwire hook are already working dude

**Comment by Wertzui123** [comment]
Everything excepts minecarts works, but i wrote the list befor.

**Comment by DenielWorld** [comment]
Another suggestion - Lectern. In vanilla they interact with redstone

**Comment by Wertzui123** [comment]
Oh, yes.

**Comment by Wertzui123** [comment]
Did you changed something in this plugin in the last weeks?
