### ISSUE TITLE
Dispensers + TNT

### ISSUE THREAD

**Issue by YT-Duckyyy** [tedo0627/RedstoneCircuit#63]
Dispensers act like a dropper when inserting tnt within them. Please fix it so that dispensing tnt places and ignites it like vanilla minecraft. It would make vanilla tnt cannons so much easier and would be able to use redstone instead of using flint and steel + tnt.

**Comment by tedo0627** [comment]
It's already been implemented.

**Comment by YT-Duckyyy** [comment]
It doesn't work lol. I've tried dispensers and droppers, powered by all different types of Redstone. Dispensers currently act like a dropper when dispensing tnt. Which in Vanilla it ignites and places, not drop.

**Comment by tedo0627** [comment]
master branch
https://github.com/tedo0627/RedstoneCircuit/blob/c5f666a6868ed516bc3490cf1eb7703f7512ba48/RedstoneCircuit/src/redstone/blockEntities/BlockEntityDispenser.php#L180-L191

pmmp4 branch
https://github.com/tedo0627/RedstoneCircuit/blob/c1b6b9864b229c2b7da0946af8ec19eae1b34c84/src/tedo0627/redstonecircuit/block/dispenser/TNTDispenseBehavior.php#L13-L20

**Comment by YT-Duckyyy** [comment]
Is master branch for pm3? And how do I add a brand to an already made plugon? I'm new to all this coding stuff

**Comment by tedo0627** [comment]
The master branch is pm3.
You can download it from poggit.

**Comment by YT-Duckyyy** [comment]
Can you send me the poggit. That has tnt dispensers cause mine doesn't.

**Comment by tedo0627** [comment]
https://poggit.pmmp.io/ci/tedo0627/RedstoneCircuit/RedstoneCircuit

**Comment by YT-Duckyyy** [comment]
Do I download the latest master branch?

**Comment by tedo0627** [comment]
yes

**Comment by YT-Duckyyy** [comment]
Could you also make it so cobwebs stop gravity based blocks, like sand and gravel because right now it just falls straight through. Makes tnt cannons very hard.

**Comment by tedo0627** [comment]
The behavior should not be implemented in the Redstone Circuit.

**Comment by YT-Duckyyy** [comment]
Wdym

**Comment by tedo0627** [comment]
This plugin implements the Redstone circuit.
Redstone circuit does not include the modification of tnt to fall slowly in cobweb.
It should be implemented by other plugins or modified on the pmmp side.

**Comment by YT-Duckyyy** [comment]
No, not tnt. Sand. Sand fall slowly in cobwebs. Its a redstone feature in vanilla Minecraft so it should be added.

**Comment by tedo0627** [comment]
Even if it's sand, I don't implement it for the same reason.

**Comment by YT-Duckyyy** [comment]
Any ideas of any plugins that may do it

**Comment by tedo0627** [comment]
I don't know.
