### ISSUE TITLE
Dispenser et Dropper drops not working

### ISSUE THREAD

**Issue by iBalix** [tedo0627/RedstoneCircuit#66]
Hi, when I use a Dispenser or Dropper and activate it, the item spawns but disappears an half second later.

As you can see in the following GIF (don't take care of the goldden nugget)

https://gyazo.com/dea25c6da74c2a2c078a8b563f00d037

**Comment by tedo0627** [comment]
Please try it with this plugin only enabled.
In my environment, items do not disappear in 0.5 seconds.

**Comment by iBalix** [comment]
Ok thanks I'll try iy
