### ISSUE TITLE
Command block not loaded until activation

### ISSUE THREAD

**Issue by iBalix** [tedo0627/RedstoneCircuit#67]
Hi, I have a a problem with the command blocks.

1) I place and setup a command block
2) Restart the server
3) Open the command block => Problem: The command block is empty, no settings seems to have been saved
4) I activate the command block with redstone torch for example => The command block settings are back

To resume, I need to activate the command block in order to see their settings (commands, delay etc...)

Can you try to load it on block/tile load instead of tile activation ?

**Comment by tedo0627** [comment]
I was able to confirm this bug.
However, we could not find the cause of this bug.

**Comment by tedo0627** [comment]
It's resolved.
