### ISSUE TITLE
"Tag "MouthMoving" does not exist"

### ISSUE THREAD

**Issue by edwinyoo44** [tedo0627/RedstoneCircuit#69]
When I finish placing the dragon's head and the server restarts

The following error occurs

`
2022-02-14 [17:24:17.019] [Server thread/ERROR]: [World: Survival-2] [Loading chunk -22 73] Bad tile entity data at list position 115: Tag "MouthMoving" does not exist
2022-02-14 [17:24:17.020] [Server thread/CRITICAL]: pocketmine\data\SavedDataLoadingException: "Tag "MouthMoving" does not exist" (EXCEPTION) in "pmsrc/src/block/tile/TileFactory" at line 133
--- Stack trace ---
  #0 pmsrc/src/world/World(2555): pocketmine\block\tile\TileFactory->createFromData(object pocketmine\world\World#29795, object pocketmine\nbt\tag\CompoundTag#137360)
  #1 pmsrc/src/world/World(2482): pocketmine\world\World->initChunk(integer -22, integer 73, object pocketmine\world\format\io\ChunkData#136935)
  #2 pmsrc/src/world/World(704): pocketmine\world\World->loadChunk(integer -22, integer 73)
  #3 pmsrc/src/world/World(2864): pocketmine\world\World->registerChunkLoader(object anonymous@pmsrc/src/world/World#L2863#127104, integer -22, integer 73)
  #4 pmsrc/src/world/World(2889): pocketmine\world\World->checkChunkPopulationPreconditions(integer -22, integer 73)
  #5 pmsrc/src/Server(576): pocketmine\world\World->requestChunkPopulation(integer -22, integer 73, NULL )
  #6 pmsrc/src/network/mcpe/NetworkSession(228): pocketmine\Server->createPlayer(object pocketmine\network\mcpe\NetworkSession#129186, object pocketmine\player\XboxLivePlayerInfo#129127, true, object pocketmine\nbt\tag\CompoundTag#129120)
  #7 pmsrc/src/network/mcpe/NetworkSession(689): pocketmine\network\mcpe\NetworkSession->createPlayer()
  #8 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(142): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #9 pmsrc/vendor/pocketmine/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#132178)
  #10 pmsrc/src/network/mcpe/NetworkSession(395): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#129027)
  #11 pmsrc/src/network/mcpe/NetworkSession(358): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#132178, string[4] ....)
  #12 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7] c.`a`..)
  #13 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 1, string[16] ..CX.s0.D...E../)
  #14 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#32356)
  #15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #17 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1644830657.0099)
  #18 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #19 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[40] /home/edwinyoo44/MinecraftBEServer/pmmp/, string[48] /home/edwinyoo44/MinecraftBEServer/pmmp/plugins/)
  #20 pmsrc/src/PocketMine(327): pocketmine\server()
  #21 pmsrc(11): require(string[90] phar:///home/edwinyoo44/MinecraftBEServer/pmmp/PocketMine-MP_4.2.0.phar/src/Pock)
--- Previous ---
pocketmine\nbt\NoSuchTagException: "Tag "MouthMoving" does not exist" (EXCEPTION) in "pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag" at line 159
  #0 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(170): pocketmine\nbt\tag\CompoundTag->getTagValue(string[11] MouthMoving, string[26] pocketmine\nbt\tag\ByteTag, NULL )
  #1 plugins/RedstoneCircuit_3.0.0.phar/src/tedo0627/redstonecircuit/block/entity/BlockEntitySkull(14): pocketmine\nbt\tag\CompoundTag->getByte(string[11] MouthMoving)
  #2 pmsrc/src/block/tile/TileFactory(131): tedo0627\redstonecircuit\block\entity\BlockEntitySkull->readSaveData(object pocketmine\nbt\tag\CompoundTag#137360)
  #3 pmsrc/src/world/World(2555): pocketmine\block\tile\TileFactory->createFromData(object pocketmine\world\World#29795, object pocketmine\nbt\tag\CompoundTag#137360)
  #4 pmsrc/src/world/World(2482): pocketmine\world\World->initChunk(integer -22, integer 73, object pocketmine\world\format\io\ChunkData#136935)
  #5 pmsrc/src/world/World(704): pocketmine\world\World->loadChunk(integer -22, integer 73)
  #6 pmsrc/src/world/World(2864): pocketmine\world\World->registerChunkLoader(object anonymous@pmsrc/src/world/World#L2863#127104, integer -22, integer 73)
  #7 pmsrc/src/world/World(2889): pocketmine\world\World->checkChunkPopulationPreconditions(integer -22, integer 73)
  #8 pmsrc/src/Server(576): pocketmine\world\World->requestChunkPopulation(integer -22, integer 73, NULL )
  #9 pmsrc/src/network/mcpe/NetworkSession(228): pocketmine\Server->createPlayer(object pocketmine\network\mcpe\NetworkSession#129186, object pocketmine\player\XboxLivePlayerInfo#129127, true, object pocketmine\nbt\tag\CompoundTag#129120)
  #10 pmsrc/src/network/mcpe/NetworkSession(689): pocketmine\network\mcpe\NetworkSession->createPlayer()
  #11 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(142): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #12 pmsrc/vendor/pocketmine/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#132178)
  #13 pmsrc/src/network/mcpe/NetworkSession(395): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#129027)
  #14 pmsrc/src/network/mcpe/NetworkSession(358): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#132178, string[4] ....)
  #15 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7] c.`a`..)
  #16 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 1, string[16] ..CX.s0.D...E../)
  #17 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#32356)
  #18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #19 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #20 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1644830657.0099)
  #21 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #22 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[40] /home/edwinyoo44/MinecraftBEServer/pmmp/, string[48] /home/edwinyoo44/MinecraftBEServer/pmmp/plugins/)
  #23 pmsrc/src/PocketMine(327): pocketmine\server()
  #24 pmsrc(11): require(string[90] phar:///home/edwinyoo44/MinecraftBEServer/pmmp/PocketMine-MP_4.2.0.phar/src/Pock)
--- End of exception information ---
`

**Comment by tedo0627** [comment]
I can confirm that error.
I'll fix it.

**Comment by tedo0627** [comment]
It's resolved.
