### ISSUE TITLE
Call to protected method pocketmine\block\Concrete::writeStateToMeta()

### ISSUE THREAD

**Issue by edwinyoo44** [tedo0627/RedstoneCircuit#71]
`
2022-02-17 [18:18:22.436] [Server thread/CRITICAL]: Error: "Call to protected method pocketmine\block\Concrete::writeStateToMeta() from scope tedo0627\redstonecircuit\block\power\BlockObserver" (EXCEPTION) in "plugins/RedstoneCircuit_dev-55.phar/src/tedo0627/redstonecircuit/block/power/BlockObserver" at line 85
--- Stack trace ---
  #0 pmsrc/src/world/World(871): tedo0627\redstonecircuit\block\power\BlockObserver->onNearbyBlockChange()
  #1 pmsrc/src/world/World(807): pocketmine\world\World->actuallyDoTick(integer 9834)
  #2 pmsrc/src/world/WorldManager(362): pocketmine\world\World->doTick(integer 9834)
  #3 pmsrc/src/Server(1775): pocketmine\world\WorldManager->tick(integer 9834)
  #4 pmsrc/src/Server(1657): pocketmine\Server->tick()
  #5 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #6 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[40] /home/edwinyoo44/MinecraftBEServer/pmmp/, string[48] /home/edwinyoo44/MinecraftBEServer/pmmp/plugins/)
  #7 pmsrc/src/PocketMine(327): pocketmine\server()
  #8 pmsrc(11): require(string[90] phar:///home/edwinyoo44/MinecraftBEServer/pmmp/PocketMine-MP_4.2.0.phar/src/Pock)
--- End of exception information ---
`

**Comment by tedo0627** [comment]
I have fixed this problem.
Thank you.
