### ISSUE TITLE
Redstone status error

### ISSUE THREAD

**Issue by udachin26** [tedo0627/RedstoneCircuit#79]
**Describe the bug**
When creating a redstone short circuit, I connect a lamp to the circuit and the system breaks down (the signal becomes active, even if the circuit is made again). Therefore, the flashing of the lamp did not work for me.

**Screenshots or videos**
I'll take a video and add it here.

**OS and versions**
 - PocketMine-MP: 4.2.3
 - Server OS: Windows 10
 - Plugin: [RedstoneCircuit](https://github.com/tedo0627/RedstoneCircuit)

**Comment by udachin26** [comment]
[VIdeo ](https://youtu.be/_K4T29jJL9Q)

**Comment by tedo0627** [comment]
I have confirmed this bug.
But it will take some time to fix it because we don't know the cause yet.

**Comment by tedo0627** [comment]
I have fixed it.
Thank you.
