### ISSUE TITLE
Comporator status switching error

### ISSUE THREAD

**Issue by udachin26** [tedo0627/RedstoneCircuit#80]
**Describe the bug**
Comporator status switching error (When switching the comorator, the behavior of the signal is inexplicable). And, it seems to me, the redstone signal update error for the block (When a signal is transmitted, the lamp seems to be updated regardless of the signal).

I also noticed that the load on the server is growing. Maybe it has something to do with the update of the block.

**Screenshots or videos**

- [server video](https://youtu.be/D8ed4sU3HSM)
- [vanilla video](https://youtu.be/wvqvdud4H0M)

**OS and versions**
 - PocketMine-MP: 4.2.3
 - Server OS: Windows 10

**Comment by udachin26** [comment]
Regarding the update of the block. If you look at the mechanics of vanilla, then it seems to me that the update of the redstone block there depends on another number of ticks

**Comment by tedo0627** [comment]
It appears that it was not a signal error due to a different behavior when the lamp signal was momentarily turned off. I will fix this.
Also, I don't understand the comparator error.
It is an inherent specification that the server load will be increased. I don't know how to make it any lighter.
