### ISSUE TITLE
Piston

### ISSUE THREAD

**Issue by niftyapple** [tedo0627/RedstoneCircuit#82]
**Describe the bug**
When implementing this plugin, it doesn't appear pistons are being loaded. I can see its been added to this code, and on the pmmp.io site as well as in the description, but when the game loads its nowhere to be found.

**To Reproduce**
1. Create new fresh server
2. add this plugin
3. start server
4. Launch game into server and check for piston

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**OS and versions**
 - PocketMine-MP:4.2.4
 - Server OS: Ubuntu
 - Plugin: 3.0.2

**Plugins**
  --- just this one
   thats what I am testing

**Crashdump, backtrace or other files** none
![ApplicationFrameHost_SILELdmq5I](https://user-images.githubusercontent.com/2738778/159169610-cd505aff-bd05-4a34-baa8-bb0375d4b162.png)

**Comment by tedo0627** [comment]
That bug has already been fixed.
Please wait until the plugin is released or use the one in development
