### ISSUE TITLE
Sticky piston can't grab another sticky piston

### ISSUE THREAD

**Issue by MrBlasyMSK** [tedo0627/RedstoneCircuit#83]
**Describe the bug**
I am trying to make an automatic door, and the piston does not grip the other piston.

**To Reproduce**
Video tutorial of what should happen: https://youtu.be/Dgq-najpSbk?t=435 (It is also useful to know how to build the automatic door in case you need to try it yourself)
Video of what actually happens: https://streamable.com/1ha3uy

**Screenshots or videos**
X

**OS and versions**
 - PocketMine-MP: 4.2.4
 - Server OS: linux
 - Plugin: Dev73

**Plugins**

 Plugins (4): DimensionPortals v0.1.2, MultiWorld v1.7.0-beta4, RedstoneCircuit v3.0.3, VanillaGenerator v0.0.4

Yes, i have tried whitout plugins
**Crashdump, backtrace or other files**
X

**Comment by tedo0627** [comment]
This is probably an observer bug, not a piston bug.
Because in vanilla there is a bug that causes the observer delay to be 4 ticks, and I believe this plugin fixes that and the circuit is not working correctly because the delay is 2 ticks.
source: https://minecraft.fandom.com/wiki/Observer

**Comment by tedo0627** [comment]
I changed the observer delay to 4 ticks and the 2 click repeater at the back of the circuit to 3 clicks and it worked!
I'm thinking this is because the piston shrinks a little late in the process, so it needs to be 3 clicks.
I'll figure out the cause of this later.

**Comment by MrBlasyMSK** [comment]
I was think this plugin is working like redstone in Bedrock

**Comment by tedo0627** [comment]
That's right.
So I am wondering if I should fix the vanilla bug and make it 2 ticks or leave the bug alone and make it 4 ticks
Which would you choose?

**Comment by MrBlasyMSK** [comment]
> That's right. So I am wondering if I should fix the vanilla bug and make it 2 ticks or leave the bug alone and make it 4 ticks Which would you choose?

I don't understand anything about redstone and I don't want to give my opinion without knowing but I would like it to work like in Minecraft Bedrock since the software (Pocketmine) is for Minecraft bedrock servers

**Comment by tedo0627** [comment]
I have fixed it.
Thank you.

**Comment by MrBlasyMSK** [comment]
> I have fixed it. Thank you.

Thx for fix it! it works now
