### ISSUE TITLE
Sticky piston can't grab a block if there is another sticky piston?

### ISSUE THREAD

**Issue by MrBlasyMSK** [tedo0627/RedstoneCircuit#84]
**Describe the bug**
This is another variant that can occur, you move the bottom piston, then the top piston, then you turn off the top piston, then the bottom piston and the block holding the top piston magically releases.

**To Reproduce**
Video of how to do it: https://streamable.com/fvw111

**Screenshots or videos**
X

**OS and versions**
 - PocketMine-MP: 4.2.4
 - Server OS: linux
 - Plugin: Dev73

**Plugins**

 Plugins (4): DimensionPortals v0.1.2, MultiWorld v1.7.0-beta4, RedstoneCircuit v3.0.3, VanillaGenerator v0.0.4

Yes, i have tried whitout plugins
**Crashdump, backtrace or other files**
X

**Comment by tedo0627** [comment]
This is not a bug.
The same behavior is observed in vanilla
