### ISSUE TITLE
Dispenser doesn't throw Splash Potion

### ISSUE THREAD

**Issue by alvin0319** [tedo0627/RedstoneCircuit#85]
**Describe the bug**
Dispenser doesn't throw Splash Potion

**To Reproduce**
1. Place dispenser
2. Add Splash Potion to Dispenser inventory
3. Activate Dispenser

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

https://user-images.githubusercontent.com/32565818/159881227-5f7c5c59-5f97-4472-9c25-2344c0749eaa.mp4

**OS and versions**
 - PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/05a5e5eac126064583af2e892cb9b3cc0b0a88b6
 - Server OS: Windows 11
 - Plugin: 3.0.3

**Plugins**

 ```
[17:08:12.024] [Server thread/INFO]: Plugins (38): AuctionHouse v1.0.0, Bank v1.0.0, BetterVoting v2.0.2, BlocksConverter v3.0.0, BuilderTools v1.3.1, ClearLag v1.0.0, CombatLogger v1.0.0, CosmoCore v1.0.0, CosmoLevel v1.0.0, CosmoQ
uest v1.0.0, DEVirion v1.2.5-ALPHA12, Dungeon v1.0.0, EconomyAPI v1.0.0, ExpansionPack v0.1.1, FloatingText v1.0.0, Fly v1.0.0, GroupsAPI v1.0.0, InventorySynchronizer v1.0.0, KDR v1.0.0, KitUI v1.0.0, Market v1.0.0, MineMonster v1.
0.0, MineReset v1, MineSystem v1.0.0, Minions v1.5, MultiWorld v1.0.0, MysteryBox v1.0.0, NetheriteAddon v1.0.0, PlayerJoinQuitMessage v1.0.0, PureEntities v2.0.0, Reboot v1.0.0, RedstoneCircuit v3.0.3, ScoreHud v7.0.0, ScoreHudAddon v1.0.0, SkyBlock v1.0.0, Tebex v0.1.1, Warp v1.0.0, WorldGuard v1.0.0
```

**Crashdump, backtrace or other files**
N/A

**Comment by tedo0627** [comment]
Previously it was not possible to get the type of splash potion, so it was not implemented, but now that it is possible I will implement it.

**Comment by tedo0627** [comment]
I implemented it.
