### ISSUE TITLE
[FR] Fireworks functional with dispenser

### ISSUE THREAD

**Issue by MrBlasyMSK** [tedo0627/RedstoneCircuit#87]
https://streamable.com/sqet5i

The plugin who add the fireworks is https://github.com/CLADevs/VanillaX

**Comment by tedo0627** [comment]
That plugin is not released by poggit and therefore cannot be used with this plugin (from poggit rule B5).
Also, because of the cost of implementing all the items that can be used in the dispenser, we only implement items that work in pmmp. We will not implement fireworks for this reason.

**Comment by MrBlasyMSK** [comment]
Oh ok, thx
