### ISSUE TITLE
Item elevator is constantly in operation

### ISSUE THREAD

**Issue by MrBlasyMSK** [tedo0627/RedstoneCircuit#89]
**Describe the bug**
I have created an object elevator which when receiving an object in the hopper, what it does is to raise it with releases (if it is badly translated blame deepl).
What happens is that the system does not stop working, even if the hopper has not picked up any object the system continues to be active.

**To Reproduce**
what happen: https://streamable.com/k5x0bc
expected: https://youtu.be/3pqm65aaB0U?t=67

**Screenshots or videos**
up is a video

**OS and versions**
 - PocketMine-MP: 4.2.5
 - Server OS: linux
 - Plugin: dev79

**Plugins**
 So many
 nop i didnt test it

**Crashdump, backtrace or other files**
x

**Comment by MrBlasyMSK** [comment]
Wait i press enter, im gonna edit

**Comment by MrBlasyMSK** [comment]
Ok i finish editing, sorry

**Comment by tedo0627** [comment]
I can confirm this bug.
I will fix it.

**Comment by tedo0627** [comment]
I have fixed it.
Thank you.
