### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DenielWorld** [tedo0627/RedstoneCircuit#9]
Dispensers are not fully implemented. They should be able to also do the following.
- Put armor on a person
- Throw projectiles (potions or arrows)
- Spawn entities (spawn eggs) [could be set through the meta of spawn egg, as the spawn egg meta and network id are the same]
- Flint and steel place fire
P.s If it was added, dispensers I think would be complete. Again thank you for the hard work.

**Comment by DenielWorld** [comment]
Bug: Bonemeal used on crop through dispenser closes server

**Comment by tedo0627** [comment]
I fixed this bug.

**Comment by DenielWorld** [comment]
Great. Also another suggestion minecarts and rails?

**Comment by tedo0627** [comment]
I plan to implement it

**Comment by DenielWorld** [comment]
BlockRedstoneComparatorPowered, should relplace 'ENtity' with 'Entity' probably?

**Comment by DenielWorld** [comment]
I think it would be great for command blocks if the @ worked, @s (sender) would apply to the person who caused the power source.

**Comment by Wertzui123** [comment]
Yea, that would be awesome

**Comment by DenielWorld** [comment]
I tested pistons, and looks like they are almost done. Although they erase blocks, not move, and you cant stand on the arm.

**Comment by Wertzui123** [comment]
So, what do you mean? Are pistons now implemented in the plugin?

**Comment by DenielWorld** [comment]
No, but there indev

**Comment by DenielWorld** [comment]
New Issue: Server crashes on join

Call to undefined method pocketmine\block\Air::getFace()

In file BlockEntityPistonArm.php in folder blockEntities on line 190

**Comment by DenielWorld** [comment]
Sorry, false report

**Comment by DenielWorld** [comment]
Crash when a piston pushes another piston

**Comment by DenielWorld** [comment]
When a piston pushes another piston towards a piston arm server crashes

**Comment by DenielWorld** [comment]
Also when a hopper has an item in it, and then gets moved by piston and gets attached to an object with inventory, the item doesnt transfer

**Comment by DenielWorld** [comment]
Just a reminder to make a fork of FactionsPE with fixed dispenser damage glitch. Thanks.
