### ISSUE TITLE
Hopper dont work + dupe

### ISSUE THREAD

**Issue by MrBlasyMSK** [tedo0627/RedstoneCircuit#90]
**Describe the bug**
I have tried to create an automatic clock with a new method but apparently the hoopers are only able to pass 1 block and return it instead of passing the whole stack and then returning it

**To Reproduce**
1. Video
2. Video

**Screenshots or videos**
https://youtu.be/KFYInH-klZU < Plugin
https://streamable.com/ip4u0e < Minecraft bedrock

**OS and versions**
 - PocketMine-MP: 4.2.6
 - Server OS: linux
 - Plugin: Dev81

**Plugins**

**Crashdump, backtrace or other files**
X

**Comment by tedo0627** [comment]
I have fixed it.
Thank you.
