### ISSUE TITLE
Observer just go brrrrr

### ISSUE THREAD

**Issue by MrBlasyMSK** [tedo0627/RedstoneCircuit#91]
**Describe the bug**
Just watch the video

**To Reproduce**
1. X
2. X

**Screenshots or videos**
https://streamable.com/4skks1 < Plugin
https://youtu.be/ZrmqFMWXIDw?t=323 < supp to be
**OS and versions**
 - PocketMine-MP: 4.2.6
 - Server OS: linux
 - Plugin: dev81

**Plugins**

**Crashdump, backtrace or other files**
X

**Comment by tedo0627** [comment]
I could not reproduce the observer block trembling
However, I was able to confirm that the redstone ramp is not as shown in the video. This is a problem that cannot be solved due to pmmp specifications

**Comment by MrBlasyMSK** [comment]
I think there is some plugin interfering with the observer, I don't know which one because I don't have one that adds that function, but I will look to see if I can find out which one it is.

**Comment by MrBlasyMSK** [comment]
Its a "INether" plugin bug, i will rep it
