### ISSUE TITLE
Pistons make a block disappear but then it appears

### ISSUE THREAD

**Issue by MrBlasyMSK** [tedo0627/RedstoneCircuit#92]
**Describe the bug**
With the automatic door that I made previously and which reported several bugs, if you step on the pressure plate too often you can make a block disappear, but then if you step on it again it appears

**To Reproduce**
1. Dont know

**Screenshots or videos**
https://streamable.com/rditc3

**OS and versions**
 - PocketMine-MP: 4.2.6
 - Server OS: linux
 - Plugin: dev81

**Plugins**

**Crashdump, backtrace or other files**
X

**Comment by tedo0627** [comment]
This behavior is similar in vanilla
So please tell the circuit maker

**Comment by MrBlasyMSK** [comment]
You have the video of how to do it in other issues

**Comment by tedo0627** [comment]
?

**Comment by tedo0627** [comment]
This circuit is buggy even in vanilla to begin with, so please tell the creator of the circuit

**Comment by MrBlasyMSK** [comment]
> This circuit is buggy even in vanilla to begin with, so please tell the creator of the circuit

https://streamable.com/1awvh9

It works perfc in a normal world, if u want to try it byurself check the video: https://www.youtube.com/watch?v=Dgq-najpSbk&t

**Comment by tedo0627** [comment]
I created the circuit for that video in vanilla and had the same phenomenon

**Comment by MrBlasyMSK** [comment]
> I created the circuit for that video in vanilla and had the same phenomenon

But this plugin is supposed to be made for bedrock, isn't it?

**Comment by tedo0627** [comment]
The behavior which you think bug is a spec. I have confirmed this behavior not only in pmmp. if you want to fix the door behavior, you need to modify your redstone circuit.
And while this plugin is designed to reproduce bedrock redstone circuits, there are some specifications that cannot be reproduced due to pmmp specifications, or cannot be reproduced based solely on the information in the wiki.

**Comment by MrBlasyMSK** [comment]
ok
