### ISSUE TITLE
Sticky piston update

### ISSUE THREAD

**Issue by MrBlasyMSK** [tedo0627/RedstoneCircuit#96]
**Describe the bug**
Sticky pistons when activated appear with an "update" block.

**To Reproduce**
1. Place a sticky piston
2. Active it whit redstone

**Screenshots or videos**
![Captura de pantalla (544)](https://user-images.githubusercontent.com/85447029/164265161-988ee1dc-5b47-43f7-aac0-8e9fc2c32748.png)

**OS and versions**
 - PocketMine-MP: 4.3.0
 - Server OS: linux
 - Plugin: dev82

**Plugins**

**Crashdump, backtrace or other files**

**Comment by tedo0627** [comment]
I have fixed it.
Thank you.
