### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PushkarOP** [tedo0627/RedstoneCircuit#97]
Hopper duplicate items

**Comment by tedo0627** [comment]
I can't fix the bug from the little info I have from you
Please fill in the template exactly as it is or give me as much information as possible

**Comment by PushkarOP** [comment]
> I can't fix the bug from the little info I have from you Please fill in the template exactly as it is or give me as much information as possible

When we put one item in hopper
So when it comes to chest it becomes two

**Comment by tedo0627** [comment]
I don't get that bug in my environment.
